### ISSUE TITLE
Missing back button on demandshaper menu

### ISSUE THREAD

**Issue by TrystanLea** [emoncms/demandshaper#13]
Its not possible to easily navigate back to the main inputs/feeds etc menu from the demandshaper menu:
![image](https://user-images.githubusercontent.com/503186/59611519-623bc080-9113-11e9-9f91-6d7b87a69c7e.png)

**Comment by emrysr** [comment]
I'm on master and I see the link back to the emoncms menu:
![demandshaper-menu](https://user-images.githubusercontent.com/1466013/59662607-3832de80-91a5-11e9-8ee0-645aad43d98e.gif)

Its should work if you're `*_menu.php` file looks like this:
https://github.com/emoncms/demandshaper/blob/master/demandshaper-module/demandshaper_menu.php

**Comment by jpalo** [comment]
Is it just me, or has DS link moved to top navigation so we can close this?

![image](https://user-images.githubusercontent.com/6917905/71963087-8d971180-3203-11ea-8611-5de3cb59bf33.png)

**Comment by emrysr** [comment]
@jpalo, yes this has been moved from the sidebar menu to allow access to the module from all pages.
