### ISSUE TITLE
device won't delete

### ISSUE THREAD

**Issue by danbates2** [emoncms/demandshaper#24]
Just a note.
Can't seem to delete a device.
Helpful for dev to be able to do this.

**Comment by TrystanLea** [comment]
Just tried this here and it worked fine, did you click on the bin icon top-right in the demandshaper module?

**Comment by danbates2** [comment]
Yeah I did.
I'll check again the exact way I found the buggy behaviour and will let you know.

**Comment by TrystanLea** [comment]
Is it the smartplug that is not deleting? It might be easier if you show me this in person next time we meet.

**Comment by TrystanLea** [comment]
ps: I've just merged low_write to master, timezone support for the smartplugs is now fixed and being able to see the ip address among other things. Could you confirm that your smartplugs time is UTC? I assume your running stock EmonESP timer branch?
