### ISSUE TITLE
Top banner 'Devices'

### ISSUE THREAD

**Issue by borpin** [emoncms/demandshaper#33]
It is confusing to use 'Devices' in the top banner for the Demandshaper module, when there is a 'device' module and devices in that context mean something different.

![image](https://user-images.githubusercontent.com/1322749/66034913-0cdcc100-e502-11e9-8a7e-b44010919100.png)

**Comment by TrystanLea** [comment]
yes sorry this was mistakenly committed, I will change it back

**Comment by borpin** [comment]
Complete.
