### ISSUE TITLE
Can't set time using Chrome (desktop) or Firefox (mobile)

### ISSUE THREAD

**Issue by glynhudson** [emoncms/demandshaper#4]
Using Chrome desktop version I can't seem to increment the "complete by" time, getting these errors: 
![screenshot 2019-03-02 at 22 27 41](https://user-images.githubusercontent.com/758844/53688335-731a1f00-3d3a-11e9-905d-44028d0cbc97.png)

On firefox mobile I get the following error when loading the page:
![screenshot 2019-03-02 at 22 27 15](https://user-images.githubusercontent.com/758844/53688337-76ada600-3d3a-11e9-9d07-ee3686c6e98c.png)

I managed to set the time using Chrome mobile, the '+' and '-' buttons would not work on the interface but tapping the time brought up the Android time picker

**Comment by TrystanLea** [comment]
@glynhudson do you still see this issue?
