### ISSUE TITLE
Disabling "OK to interupt" doesn't re-enable balancing.

### ISSUE THREAD

**Issue by WeeBull** [emoncms/demandshaper#45]
With the following state, the "Time left: is 1h50m", there's "105 mins left to run", it's scheduled for "3:15 to 5:00" (also 105 minutes, 1h45), and there is 3x30 minute segments highlighted to run.

Minor Issue: I'd expect any segment used, even partially, to be highlighted.

<img width="928" alt="Screenshot 2020-03-03 at 00 49 16" src="https://user-images.githubusercontent.com/326175/75731988-240a1f80-5ce9-11ea-9011-f1e7a79a8ff3.png">

Settings:

- Battery Capacity: 27kWh
- AC Charge Rate: 7.4 kW
- Balancing %: 95%
- Balancing Time: 90 mins
- Current SoC: 91%
- Target Soc: 100%
- OK to Interrupt: False
- Time to complete: 16:00

Switching "Ok to Interrupt" to true causes a recalculation where balancing is ignored, and a single 30m segment is scheduled.

<img width="931" alt="Screenshot 2020-03-03 at 01 02 06" src="https://user-images.githubusercontent.com/326175/75732539-a1825f80-5cea-11ea-8f62-28d546b96546.png">

**Main Issue:** Returning "Ok to Interrupt" to False leaves us with the same solution, and only a single 30m segment scheduled.

<img width="915" alt="Screenshot 2020-03-03 at 01 14 02" src="https://user-images.githubusercontent.com/326175/75733110-4cdfe400-5cec-11ea-86a4-c8ff4d8ef0bd.png">

Changing the target SoC adds the balancing time back.

**Comment by TrystanLea** [comment]
This is now fixed in the latest version
