### ISSUE TITLE
Negative Agile pricing is not displayed 

### ISSUE THREAD

**Issue by glynhudson** [emoncms/demandshaper#50]
When Agile pricing goes negative this is not displayed on the demand shaper graph

![Screenshot 2020-04-12 at 23 42 31](https://user-images.githubusercontent.com/758844/79081648-4e52f200-7d17-11ea-8d15-080582b315dd.png)

![Screenshot 2020-04-12 at 23 42 53](https://user-images.githubusercontent.com/758844/79081655-5743c380-7d17-11ea-9e34-53b91b51da1a.png)

**Comment by glynhudson** [comment]
This issue seems to have returned, testing running latest version of demand shaper negative pricing is not displayed 

![Screenshot from 2020-07-05 03-27-09](https://user-images.githubusercontent.com/758844/86524199-7ada5e00-be6f-11ea-95d8-363f01269dda.png)

![EcHjSU_WAAAjYXG](https://user-images.githubusercontent.com/758844/86524214-a0fffe00-be6f-11ea-9735-861db8ce1931.jpeg)

**Comment by TrystanLea** [comment]
This is now fixed :)
