### ISSUE TITLE
Nordpool not working

### ISSUE THREAD

**Issue by jpalo** [emoncms/demandshaper#58]
Hi,
I started fixing issue with Nordpool signal as the demandshaper_run.php always set the smart schedule to start at (complete_time-run_period), and end at (complete_time) regardless of actual signal prices, but ended up in a situation that caused stuck relay error. I assume there is some issue in the code causing rapid cycle of turning charging on/off at the time when smart schedule has started charging. Looking at the charging history, it hasn't charged at all during that time AND I see the scheduled start time being changed...as if it would modify the smart schedule during charging.

If you could take a look at this https://github.com/jpalo/demandshaper/tree/nordpoolfixes. It fixes the smart schedule timing issue (as there isn't always 24h future signal data available), but would appear to cause issues.

**Comment by TrystanLea** [comment]
Hello @jpalo I wonder if I can try to replicate the issue that you are seeing.

Testing with your Nordpool token and DK2 I see:

![image](https://user-images.githubusercontent.com/503186/97113175-7a94f580-16e0-11eb-8873-b7d1b5ee3ba4.png)

The intention of this section is that the demandshaper should use yesterdays values if there is not 24h available https://github.com/emoncms/demandshaper/blob/master/forecasts/nordpool.php#L104 

I realise I haven’t put a default in there if it cant find a valid value.. It would apply the last value which is fine if the first half hour is present... for Octopus is defaults to 12.0p/kWh if it cant find a signal value https://github.com/emoncms/demandshaper/blob/master/forecasts/octopusagile.php#L81

What device are you scheduling?

**Comment by jpalo** [comment]
I'm scheduling OpenEVSE so need to be bit more careful.

Nordpool prices for next day are released every day at around 13:30 EET, so until that there is less that 24h data forward. It should never use yesterdays values but instead just refuse to smart schedule past the last available price point. 

Think of it forcing the complete_time to 00:00 instead of 8:00 user may have defined for as long as there is no price data after 00:00. As soon as price data is available for the next day, it would update the smart schedule to respect the user defined complete_time 8:00.

I believe it did work like this before this big update, but I didn't monitor it so closely during the day time.

**Comment by TrystanLea** [comment]
I can see your point, I guess the way I was looking at it is that the demandshaper will initially schedule with perhaps some of yesterdays values but then the schedules are being continuously recalculated based on updated forecast information and so when the new prices come through it will then adjust the timing of the schedule so that its correct. This works for all interruptible schedules and all non-interruptible schedules that start after the time that the new prices become available. That was my intention in terms of the design, do you see what I mean?

**Comment by jpalo** [comment]
Note that the Expektra API won't return old values, so if you start from empty signal price data set, you'd need to use some default value. Shouldn't that default value be very high, so it would never end up selecting times from those non-existing hours? And if it would be some very high default value, couldn't it be NULL instead, and that NULL would just be ignored in start/end calculation? That was my idea how to tackle it...it would also not mess up the chart in UI.

But the logic you describe is correct I think as long as we somehow handle these two special scenarios.

**Comment by TrystanLea** [comment]
Setting a high default value is a good idea, I dont think the scheduler is designed to work with null values at the moment. 

The expektra API does not need to provide old values as the demandshaper will just use the prices that it had received yesterday until the new prices are available. It at least gives an indication to the user of the time that the schedule will occur. Generally in my experience the cheaper times are often around the same time e.g middle of the night, outside of peak hours, daytime PV peak the precise optimisation is usually the exact hour of the night. The user can see initially based on yesterday values that the charge will likely happen in the night, the exact timing is confirmed when the new prices are available.

One issue with limiting the scheduling to the hours that are available is that the demandshaper will try to schedule the charge before 13:30 EET even for a schedule that can finish the next day and is likely better scheduled at the lower prices that might become available on the next pricing update

**Comment by jpalo** [comment]
There is a critical issue with current Nordpool implementation, causing Stuck Contact ERROR on OpenEVSE. It has now occurred two times, both after enabling the latest Demandshaper with the new Nordpool implementation. 

It would appear to go to some loop ramming relay on/of quickly eventually causing it to stuck. It doesn't occur constantly, however. I don't have 100% proof of this, but I did see weird charging spikes, and intermittent failure of charging the car over night.

At this point I cannot risk testing this with my "production" OpenEVSE. I did use basic Timer since first seeing this problem when the new Nordpool implementation was released, and decided to give it another go, and immediately ran into same issue. Switching back to basic nightly Timer for now until I/we figure out how to even reproduce this issue.

It could be related to fact that Expektra stream is different in 3 ways (at least):
- it doesn't return price of CURRENT hour
- it only includes prices up until the end of next day, new prices are released sometime in the afternoon for the following day
- prices are per HOUR

I'm thinking we should improve the forecast_tester to allow testing all these scenarios, but I haven't been able to figure out the logic how everything is connected in Demandshaper in terms of redis data, demandshaper_run, scheduler2, scheduler so it is rather difficult to start creating tester for something you don't really know how it works in the first place. @TrystanLea

**Comment by TrystanLea** [comment]
Sorry @jpalo did you get to the bottom of your last hidden comment at all? Were you testing with interruptible schedules, I have a fix for this mode which I will be merging soon.

**Comment by jpalo** [comment]
Not really. I hid my comment as I wasn't at all sure anymore if the issue was at all related to Demandshaper or if it is just some hardware issue (https://community.openenergymonitor.org/t/stuck-contact/16766).

As this issue is quite vague and not necessarily software relayed, I think we can close this and I will create new issue if it in the end would seem like a software issue after all.

**Comment by TrystanLea** [comment]
Ok thanks @jpalo I've messaged Glyn to ask if he can take a look at your latest post on that thread. Thanks!
