### ISSUE TITLE
Timer setting field don't work on chrome

### ISSUE THREAD

**Issue by glynhudson** [emoncms/demandshaper#8]

**Comment by danbates2** [comment]
Firefox also, Going to the 'timer' tab, not 'smart', to set timers 1 & 2.. seems the way data is parsed at either end is faulty? could be the smartplug firmware, could be demand shaper module .js or php.? not sure...

**Comment by TrystanLea** [comment]
I've now fixed this on the low_write branch which will soon be merged to master https://github.com/emoncms/demandshaper/tree/low_write, great if you could try it @danbates2

**Comment by danbates2** [comment]
Hey, I pulled the low_write branch and it didn't work. The timer2 setting doesn't store.
Also, deleting a device to re-create the device didn't work.

**Comment by danbates2** [comment]
The emonesp firmware could be broken out into two timer sub-topics. 

![Screen Shot 2019-07-10 at 21 53 12](https://user-images.githubusercontent.com/5250782/61004190-5089b980-a35d-11e9-86af-5d50e2f6b212.png)

**Comment by danbates2** [comment]
Or this:?
![Screen Shot 2019-07-10 at 21 58 52](https://user-images.githubusercontent.com/5250782/61004459-fa694600-a35d-11e9-875e-8e115611ee73.png)

Or this. Either are better.

**Comment by TrystanLea** [comment]
I wonder if it's javascript cache,  or perhaps can you try
emoncms/demandshaper/clearall, that url resets the underlying data object

**Comment by danbates2** [comment]
Nope,
![Screen Shot 2019-07-10 at 22 11 48](https://user-images.githubusercontent.com/5250782/61005243-c1ca6c00-a35f-11e9-91f6-f2d52dee3c43.png)

Timer2 still not working.

**Comment by danbates2** [comment]
Also, the ip-address shown at the bottom was useful, it's gone now?

**Comment by danbates2** [comment]
Here we go.
general.js

![Screen Shot 2019-07-10 at 22 16 07](https://user-images.githubusercontent.com/5250782/61005582-5e8d0980-a360-11e9-9cd3-3d13197e5a87.png)

timer1 is sent but not timer2?

**Comment by danbates2** [comment]
javascript 👎

**Comment by TrystanLea** [comment]
Ah I thought you where saying both timer1 and 2 where not working, yes
timer 2 is not transferred immediately, it should transfer the first timer
period first and then the second after the first completes.

I haven't tested the timer that much though,  I mostly use on/off & smart

Yes also noticed the missing ip.. Will dig into that

**Comment by danbates2** [comment]
Srry mate, defo not working here. I'll reflash the sonoff just to be sure.

**Comment by danbates2** [comment]
The 'time now' displayed on emonesp is also not time-zone compatible?

**Comment by TrystanLea** [comment]
Is timer1 transferring for you? The period described by timer2 should transfer to timer1 after timer1 completes.

**Comment by danbates2** [comment]
So. Setting timer 1 and 2 on emonESP can be loaded into the demandshaper module. However, only changes to timer1 can be made in the demandshaper. timer2 not.

**Comment by TrystanLea** [comment]
Not quite, timer2 will apply but not written to the timer2 position on emonESP instead it will end up getting written to the timer1 position after timer1 completes. It might be possible to improve on this, to write to both timer1 and timer2 on emonESP but the end result in terms of seen behaviour should be the same.

**Comment by danbates2** [comment]
Gotcha. I've checked that, and timer1 and 2 work fine. Working.
so within emonESP, the timer2 is not being displayed correctly.
